#!/usr/bin/env sh

git log -1 --pretty=%B | grep -q Release

if [ $? -eq 0 ]; then
    VERSION=$(cat .version)
    echo "==> Bulding... v$VERSION"
    
    docker build -t tutum.co/zuppler/customer-service .
else
    echo '==> Skip build.'
fi
