#!/usr/bin/env sh

git log -1 --pretty=%B | grep -q Release

if [ $? -eq 0 ]; then
    VERSION=$(cat .version)
    echo "==> Releasing ... v$VERSION"
    
    docker push tutum.co/zuppler/customer-service
else
    echo '==> Skip release.'
fi
